import pandas as pd
import numpy as np
import os

data_path = {
    'bdd':{
        'DET Veh':'',
        'DET Hum':'',
        'EXP Veh':"/mnt/h/OneDrive - The University Of Hong Kong/bdd/results/explanation/231018_vehicle_whole_screen_vb_fixed_pos/veh_exp_cleaned_outliers_11_23_2023_02_18_with_duration.xlsx",
        'EXP Hum':"/mnt/h/OneDrive - The University Of Hong Kong/bdd/results/explanation/231018_human_whole_screen_vb_fixed_pos/hum_exp_cleaned_outliers_11_30_2023_01_11_with_duration.xlsx"
    },
    'mscoco':{
        'PV':'/mnt/h/OneDrive - The University Of Hong Kong/mscoco/fixation/with_duration_pv_fix_11_14_2023_14_45.xlsx',
        'DET':'/mnt/h/OneDrive - The University Of Hong Kong/mscoco/fixation/with_duration_detection_veh_fix_11_06_2023_17_58.xlsx',
        'EXP':'/mnt/h/OneDrive - The University Of Hong Kong/mscoco/fixation/with_duration_explanation_fix_11_14_2023_14_24.xlsx',
        'DET_excluded':'/mnt/h/OneDrive - The University Of Hong Kong/mscoco/fixation/cocluster_with_duration_det_fix_11_18_2023_12_18.xlsx',
        'EXP_excluded':'/mnt/h/OneDrive - The University Of Hong Kong/mscoco/fixation/cocluster_with_duration_exp_fix_11_18_2023_12_31.xlsx'
    }
}

output_path = {
    'bdd':{
        'DET Veh':'',
        'DET Hum':'/mnt/h/Projects/HKU_XAI_Project/XAI_Similarity_1/Hum_IdTask_Split_Fixation', # found in guoyang's folder (generated by Alice previously?)
        'EXP Veh':'', # same folder as the input
        'EXP Hum':''
    },
    'mscoco':{
        'PV': '/mnt/h/OneDrive - The University Of Hong Kong/mscoco/fixation/split_by_id/PV',
        'DET': '/mnt/h/OneDrive - The University Of Hong Kong/mscoco/fixation/split_by_id/DET',
        'EXP': '/mnt/h/OneDrive - The University Of Hong Kong/mscoco/fixation/split_by_id/EXP',
        ## Exclude subject with missing blocks
        'DET_excluded': '/mnt/h/OneDrive - The University Of Hong Kong/mscoco/fixation/split_by_id/DET_excluded',
        'EXP_excluded': '/mnt/h/OneDrive - The University Of Hong Kong/mscoco/fixation/split_by_id/EXP_excluded'
    }
}

for data in ['mscoco']:
    for condition in data_path[data]:

        if not os.path.exists(output_path[data][condition]):
            os.makedirs(output_path[data][condition])

        df = pd.read_excel(data_path[data][condition])

        # Different label naming used by Mary and Jinhan
        if data == 'mscoco':
            df.rename(columns={'FixX': 'CURRENT_FIX_X', 'FixY': 'CURRENT_FIX_Y', 'FixDuration':'CURRENT_FIX_DURATION','StimuliID':'img','SubjectID':'sessionLabel'}, inplace=True)
        elif data == 'bdd':
            df.rename(columns={'FixX': 'CURRENT_FIX_X', 'FixY': 'CURRENT_FIX_Y', 'FixD':'CURRENT_FIX_DURATION','StimuliID':'img','SubjectID':'sessionLabel'}, inplace=True)
        df = df[['CURRENT_FIX_X','CURRENT_FIX_Y','CURRENT_FIX_DURATION','img','sessionLabel']]

        grouped = df.groupby('img')

        for name, group in grouped:
            group.to_excel(os.path.join(output_path[data][condition],f"{name.replace('.png','')}.xlsx"),index=False)